spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:madiecqllibrary}
      uri: ${MONGO_URI:mongodb://${DBUSER}:${DBPASS}@localhost:27017/madiecqllibrary}?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000


server:
  port: 8082
  servlet:
    context-path: /api

madie:
  allowedApi: http://localhost:9000
  fhir:
    service:
      baseUrl: ${FHIR_SERVICES_URL:http://localhost:8085/api}
      hapi-fhir:
        libraries:
          uri: /hapiFhir/libraries
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-18092578.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}

hapi-fhir:
  url: ${HAPI_FHIR_URL:http://localhost:8087/fhir}
  patient:
    uri: /Patient
