spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:madiecqllibrary}
      uri: ${MONGO_URI:mongodb://${DBUSER}:${DBPASS}@localhost:27017/madiecqllibrary}?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000

server:
  port: 8082
  servlet:
    context-path: /api

madie:
  allowedApi: http://localhost:9000
  measure-service:
    base-url: ${MEASURE_SERVICE_URL:http://localhost:8080/api}
  cql-elm:
    service:
      qdm-base-url: ${QDM_ELM_TRANSLATOR_SERVICE_URL:http://localhost:8084/api/qdm}
      fhir-base-url: ${FHIR_ELM_TRANSLATOR_SERVICE_URL:http://localhost:8083/api/fhir}
      elm-json-uri: /cql/translator/cql
  user-service:
    base-url: ${USER_SERVICE_URL:http://localhost:8088/api}
  service-config:
    json-url: ${SERVICE_CONFIG_JSON_URL:http://localhost:9000/env-config/serviceConfig.json}
  excel-export-service:
    base-url: ${EXCEL_EXPORT_SERVICE:http://localhost:3000/api}
    libraries:
      access-report-api-path: /excel/library-shared-access-report

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-madie.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}

mongock:
  migration-scan-package:
    - gov.cms.madie.cqllibraryservice.config