spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:madiecqllibrary}
      uri: ${MONGO_URI:mongodb://${DBUSER}:${DBPASS}@localhost:27017/madiecqllibrary}?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000

server:
  port: 8082
  servlet:
    context-path: /api

madie:
  allowedApi: http://localhost:9000
  cql-elm:
    service:
      qdm-base-url: ${QDM_ELM_TRANSLATOR_SERVICE_URL:http://localhost:8084/api/qdm}
      fhir-base-url: ${FHIR_ELM_TRANSLATOR_SERVICE_URL:http://localhost:8083/api/fhir}
      elm-json-uri: /cql/translator/cql
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-18092578.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}

lambda-api-key: ${LAMBDA_API_KEY:9202c9fa}

mongock:
  migration-scan-package:
    - gov.cms.madie.cqllibraryservice.config

