spring:
   data:
      mongodb:
         uri: mongodb://gakins:E5press0@madie-cql-library-mongo:27017/madiecqllibrary?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000

